### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by umarkhalidAI** [tiangexiang/OccNeRF#1]
When do you intend to release the code?

**Comment by tiangexiang** [comment]
Thanks for your interest! We are currently overwhelmed by CVPR submissions. We plan to release the code around mid-November.

**Comment by andrearama** [comment]
Great work. Looking forward to the code as well.
In the meantime, good luck for the CVPR submission :)

**Comment by GloryyrolG** [comment]
Any update, please?

**Comment by tiangexiang** [comment]
Thanks for your interest. We are now doing the final cleaning, code will be released as soon as possible after the holidays. Thanks :)

**Comment by tiangexiang** [comment]
The codes are now released! Sorry for the delay. Please let me know if you encounter any problems when running the codes :)
