### ISSUE TITLE
Question about evaluation

### ISSUE THREAD

**Issue by arid29** [tiangexiang/OccNeRF#11]
Hi,

I noticed that when I run python eval.py --cfg ./configs/occnerf/zju_mocap/387/occnerf.yaml for obtaining the quantitative numbers, self.occlude is set to False. Can you please explain what's going on here?

**Comment by tiangexiang** [comment]
Hi, sorry for the late response. For simulated occlusions, we can have full evaluations of the entire human body by disabling the simulated occlusions. By doing this, we are able to comprehensively validate the ability of the models on both visible and occluded regions --- so we know if the model overfits on the visible regions or in fact learns the underlying human anatomy behind occlusions.

**Comment by arid29** [comment]
thanks!
