### ISSUE TITLE
OcMotion dataset

### ISSUE THREAD

**Issue by Sulwon-0516** [tiangexiang/OccNeRF#3]
Thank you for sharing your excellent work and code! 

I was wondering if there are any plans to release configuration or checkpoints optimized for the OcMotion dataset.
I've searched but haven't been able to find them. 
If these are already available and I've overlooked them, my apologies.

**Comment by tiangexiang** [comment]
Hi, thank you for your interest. Yes, we do plan to release configurations for the OcMotion dataset in the near future (possibly before next month). Please stay tuned!
