### ISSUE TITLE
Experimental settings about OcMotion

### ISSUE THREAD

**Issue by imabackstabber** [tiangexiang/OccNeRF#8]
I'm a little confused by the OcMotion training and testing settings. I found that only frames from a single camera are provided. So it implies that the same picture for training is also used for testing...? Or I must be missing the frames used for testing? Where should I get them?

**Comment by tiangexiang** [comment]
In this paper, our evaluation on OcMotion was only conducted on the input frames and visible body parts. This is because most frames from different camera angles are blocked by obstacles, which are not able to use to compute metrics.

**Comment by imabackstabber** [comment]
I see, so the image used for training is also directly used as gt imgs when computing psnr. Is that right?

**Comment by tiangexiang** [comment]
Yes! however, we do encourage to provide renderings at different camera angles as qualitative results even if those reference images are not available for quantitative evaluations.

**Comment by imabackstabber** [comment]
Thanks for answering! I will close this issue.
